runtime: custom
env: flex

liveness_check:
   check_interval_sec: 120
   timeout_sec: 40
   failure_threshold: 5
   success_threshold: 5
   initial_delay_sec: 500

readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 1500

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  disk_size_gb: 100